# Generated by Django 5.0.4 on 2024-05-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_remove_todo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='status',
            new_name='completed',
        ),
    ]
