# Generated by Django 5.0.4 on 2024-05-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_rename_status_todo_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
